# Generated by Django 4.0.4 on 2023-06-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('channel', models.CharField(blank=True, max_length=16, null=True)),
                ('source', models.CharField(blank=True, max_length=16, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('img_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.imgurl')),
            ],
        ),
    ]
