# Generated by Django 4.0.5 on 2023-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rename_imgurl_images_rename_img_url_images_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
