# Generated by Django 4.0.5 on 2023-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_news_images_news_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='news',
            name='publish_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
