# Generated by Django 4.0.5 on 2023-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_news_channel_alter_news_publish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
