# Generated by Django 4.0.5 on 2023-07-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
